---
apiVersion: v1
kind: Service
metadata:
  name: cm-exporter-lb
spec:
  type: LoadBalancer
  ports:
  - targetPort: 8081
    port: 8081
    protocol: TCP
    name: ui
  selector:
    app: cm-exporter
  externalTrafficPolicy: Local
